-- ============================================================================
-- PARTNER USER RLS POLICY REFERENCE
-- ============================================================================
-- This document maps PARTNER MEMBER access to existing RLS policies
-- NO NEW POLICIES NEEDED - Existing policies already support partner_member role
-- ============================================================================

-- ============================================================================
-- TABLE: campaigns
-- ============================================================================
-- EXISTING POLICY: "campaigns_select_own_or_partner"
-- 
-- CREATE POLICY "campaigns_select_own_or_partner"
-- ON public.campaigns FOR SELECT
-- USING (
--   created_by_user_id = auth.uid()
--   OR partner_id = public.get_user_partner_id(auth.uid())
--   OR public.is_super_admin(auth.uid())
-- );
--
-- PARTNER MEMBER ACCESS:
--   • Condition: partner_id = public.get_user_partner_id(auth.uid())
--   • Result: ✅ Can SELECT all campaigns in own partner
--   • No INSERT policy allows partner_member → ❌ Cannot create campaigns
--   • No UPDATE policy allows partner_member → ❌ Cannot edit campaigns
--   • No DELETE policy allows partner_member → ❌ Cannot delete campaigns

-- ============================================================================
-- TABLE: programs
-- ============================================================================
-- EXISTING POLICY: "programs_select_own_or_partner"
--
-- CREATE POLICY "programs_select_own_or_partner"
-- ON public.programs FOR SELECT
-- USING (
--   created_by_user_id = auth.uid()
--   OR partner_id = public.get_user_partner_id(auth.uid())
--   OR public.is_super_admin(auth.uid())
-- );
--
-- PARTNER MEMBER ACCESS:
--   • Condition: partner_id = public.get_user_partner_id(auth.uid())
--   • Result: ✅ Can SELECT all programs in own partner
--   • No INSERT policy allows partner_member → ❌ Cannot create programs
--   • No UPDATE policy allows partner_member → ❌ Cannot edit programs
--   • No DELETE policy allows partner_member → ❌ Cannot delete programs

-- ============================================================================
-- TABLE: tasks
-- ============================================================================
-- EXISTING POLICY: "tasks_select_own_or_assigned_or_approver"
--
-- CREATE POLICY "tasks_select_own_or_assigned_or_approver"
-- ON public.tasks FOR SELECT
-- USING (
--   created_by_user_id = auth.uid()
--   OR assigned_to_user_id = auth.uid()
--   OR approver_user_id = auth.uid()
--   OR partner_id = public.get_user_partner_id(auth.uid())
--   OR public.is_super_admin(auth.uid())
-- );
--
-- PARTNER MEMBER ACCESS:
--   • Condition: partner_id = public.get_user_partner_id(auth.uid())
--   • Result: ✅ Can SELECT all tasks in own partner
--   • UPDATE policy checks: created_by_user_id = auth.uid() OR assigned_to_user_id = auth.uid()
--     → Partner member can update own tasks if assigned
--     → Partner member CANNOT update tasks created by others
--   • No INSERT policy allows partner_member → ❌ Cannot create tasks
--   • No DELETE policy allows partner_member → ❌ Cannot delete tasks

-- ============================================================================
-- TABLE: wallets
-- ============================================================================
-- EXISTING POLICY: "Users can view own wallet"
--
-- CREATE POLICY "Users can view own wallet" ON public.wallets
--   FOR SELECT USING (
--     user_id = auth.uid()
--     OR partner_id = public.get_user_partner_id(auth.uid())
--     OR is_super_admin(auth.uid())
--   );
--
-- PARTNER MEMBER ACCESS:
--   • Condition: user_id = auth.uid() (own wallet)
--   • Condition: partner_id = public.get_user_partner_id(auth.uid()) (partner wallets)
--   • Result: ✅ Can SELECT own wallet AND all partner wallets
--   • No INSERT policy allows partner_member → ❌ Cannot create wallets
--   • UPDATE policy requires is_partner_admin or is_super_admin → ❌ Cannot edit wallets
--   • No DELETE policy allows partner_member → ❌ Cannot delete wallets

-- ============================================================================
-- TABLE: team_members
-- ============================================================================
-- EXISTING POLICY: "team_members_select_own_or_admin"
--
-- CREATE POLICY "team_members_select_own_or_admin"
-- ON public.team_members FOR SELECT
-- USING (
--   user_id = auth.uid()
--   OR partner_id = public.get_user_partner_id(auth.uid())
--   OR public.is_super_admin(auth.uid())
-- );
--
-- PARTNER MEMBER ACCESS:
--   • Condition: partner_id = public.get_user_partner_id(auth.uid())
--   • Result: ✅ Can SELECT team members in own partner
--   • INSERT policy requires is_partner_admin or is_super_admin → ❌ Cannot create team members
--   • UPDATE policy requires is_partner_admin or is_super_admin → ❌ Cannot edit team members
--   • DELETE policy requires is_partner_admin or is_super_admin → ❌ Cannot delete team members

-- ============================================================================
-- TABLE: user_activity_log
-- ============================================================================
-- EXISTING POLICY: "activity_log_select_own_or_partner"
--
-- CREATE POLICY "activity_log_select_own_or_partner"
-- ON public.user_activity_log FOR SELECT
-- USING (
--   user_id = auth.uid()
--   OR partner_id = public.get_user_partner_id(auth.uid())
--   OR public.is_super_admin(auth.uid())
-- );
--
-- PARTNER MEMBER ACCESS:
--   • Condition: user_id = auth.uid() (own activities)
--   • Condition: partner_id = public.get_user_partner_id(auth.uid()) (partner activities)
--   • Result: ✅ Can SELECT own activity logs AND partner activity logs
--   • INSERT policy requires super_admin or partner_admin role → ❌ Cannot insert directly
--     (System inserts via triggers and RPC functions)
--   • UPDATE: Not allowed (immutable audit log) → ❌ Cannot edit logs
--   • DELETE: Not allowed (immutable audit log) → ❌ Cannot delete logs

-- ============================================================================
-- TABLE: user_performance_metrics
-- ============================================================================
-- EXISTING POLICY: "metrics_select_own_or_partner"
--
-- CREATE POLICY "metrics_select_own_or_partner"
-- ON public.user_performance_metrics FOR SELECT
-- USING (
--   user_id = auth.uid()
--   OR partner_id = public.get_user_partner_id(auth.uid())
--   OR public.is_super_admin(auth.uid())
-- );
--
-- PARTNER MEMBER ACCESS:
--   • Condition: user_id = auth.uid() (own metrics)
--   • Condition: partner_id = public.get_user_partner_id(auth.uid()) (partner metrics)
--   • Result: ✅ Can SELECT own metrics AND partner metrics
--   • No UPDATE policy allows direct updates (system-managed) → ❌ Cannot edit metrics
--   • No DELETE policy allows partner_member → ❌ Cannot delete metrics

-- ============================================================================
-- TABLE: profiles
-- ============================================================================
-- EXISTING POLICIES: "Users can view own profile" + "Admins can view partner members"
--
-- CREATE POLICY "Users can view own profile" ON public.profiles
--   FOR SELECT USING (
--     auth.uid() = id 
--     OR is_super_admin(auth.uid())
--   );
--
-- CREATE POLICY "Admins can view partner members" ON public.profiles
--   FOR SELECT USING (
--     auth.uid() IN (
--       SELECT id FROM public.profiles 
--       WHERE partner_id = profiles.partner_id 
--       AND role ILIKE '%admin%'
--     )
--   );
--
-- PARTNER MEMBER ACCESS:
--   • Condition: auth.uid() = id (can view own profile)
--   • Condition: partner_id match + admin role = false (regular member)
--   • Result: ✅ Can SELECT own profile
--   • Result: ❌ Cannot SELECT other profiles (not admin)
--   • UPDATE policy: auth.uid() = id (can update own) → ✅ Can edit own profile
--     (but cannot change role, partner_id, or permissions)
--   • No INSERT policy allows partner_member → ❌ Cannot create profiles (admin only)
--   • No DELETE policy allows partner_member → ❌ Cannot delete profiles

-- ============================================================================
-- TABLE: partners
-- ============================================================================
-- EXISTING POLICIES: Partner-level (partner_admin + super_admin only)
--
-- CREATE POLICY "Users can view own partner" ON public.partners
--   FOR SELECT USING (
--     id = (SELECT partner_id FROM public.profiles WHERE id = auth.uid())
--     OR is_super_admin(auth.uid())
--   );
--
-- PARTNER MEMBER ACCESS:
--   • Condition: id = (SELECT partner_id FROM profiles)
--   • Result: ✅ Can SELECT own partner record (via subquery)
--   • No INSERT policy allows partner_member → ❌ Cannot create partners
--   • UPDATE policy requires is_partner_admin or is_super_admin → ❌ Cannot edit partner
--   • No DELETE policy allows partner_member → ❌ Cannot delete partner

-- ============================================================================
-- TABLE: audit_logs
-- ============================================================================
-- EXISTING POLICIES: User-level only
--
-- CREATE POLICY "Users can view own audit logs" ON public.audit_logs
--   FOR SELECT USING (
--     user_id = auth.uid() OR is_super_admin(auth.uid())
--   );
--
-- PARTNER MEMBER ACCESS:
--   • Condition: user_id = auth.uid() (own audit log)
--   • Result: ✅ Can SELECT own audit logs only
--   • Result: ❌ Cannot view other users' or partner audit logs
--   • No UPDATE policy allows partner_member → ❌ Cannot edit logs
--   • No DELETE policy allows partner_member → ❌ Cannot delete logs

-- ============================================================================
-- TABLE: transactions
-- ============================================================================
-- EXISTING POLICIES: Wallet-related
--
-- CREATE POLICY "Users can view own transactions" ON public.transactions
--   FOR SELECT USING (
--     user_id = auth.uid()
--     OR partner_id = public.get_user_partner_id(auth.uid())
--     OR is_super_admin(auth.uid())
--   );
--
-- PARTNER MEMBER ACCESS:
--   • Condition: user_id = auth.uid() (own transactions)
--   • Condition: partner_id = public.get_user_partner_id(auth.uid()) (partner transactions)
--   • Result: ✅ Can SELECT own transactions AND partner transactions
--   • No INSERT policy allows direct insert (system/RPC only) → ❌ Cannot create transactions
--   • UPDATE policy requires is_partner_admin or is_super_admin → ❌ Cannot edit transactions
--   • No DELETE policy allows partner_member → ❌ Cannot delete transactions

-- ============================================================================
-- TABLE: withdrawals
-- ============================================================================
-- EXISTING POLICIES: Wallet-related
--
-- CREATE POLICY "Users can view own withdrawals" ON public.withdrawals
--   FOR SELECT USING (
--     user_id = auth.uid()
--     OR partner_id = public.get_user_partner_id(auth.uid())
--     OR is_super_admin(auth.uid())
--   );
--
-- PARTNER MEMBER ACCESS:
--   • Condition: user_id = auth.uid() (own withdrawals)
--   • Condition: partner_id = public.get_user_partner_id(auth.uid()) (partner withdrawals)
--   • Result: ✅ Can SELECT own withdrawals AND partner withdrawals
--   • INSERT policy allows user_id = auth.uid() → ✅ Can request own withdrawal
--   • UPDATE policy requires is_partner_admin or is_super_admin (status changes only)
--     → ❌ Cannot approve/reject withdrawals (admin only)
--   • No DELETE policy allows partner_member → ❌ Cannot delete withdrawals

-- ============================================================================
-- SUMMARY TABLE
-- ============================================================================

-- Table                    SELECT    INSERT   UPDATE   DELETE   Notes
-- ─────────────────────────────────────────────────────────────────────────
-- campaigns                ✅        ❌       ❌       ❌       View only
-- programs                 ✅        ❌       ❌       ❌       View only
-- tasks                    ✅        ❌       ~        ❌       View + update own assigned
-- wallets                  ✅        ❌       ❌       ❌       View only
-- team_members             ✅        ❌       ❌       ❌       View only
-- user_activity_log        ✅        ❌       ❌       ❌       View only (immutable)
-- user_performance_metrics ✅        ❌       ❌       ❌       View only
-- profiles                 ✅        ❌       ~        ❌       View own + edit own
-- partners                 ✅        ❌       ❌       ❌       View own partner
-- audit_logs               ✅        ❌       ❌       ❌       View own only
-- transactions             ✅        ❌       ❌       ❌       View own + partner
-- withdrawals              ✅        ✅*      ❌       ❌       View + request own, not approve
-- withdrawals_history      ✅        ❌       ❌       ❌       View only (immutable)

-- Legend:
-- ✅ = Allowed for partner_member
-- ❌ = Not allowed for partner_member
-- ~ = Partially allowed (specific conditions)
-- * = Limited (withdrawal request only, not approval)

-- ============================================================================
-- PERMISSION MAPPING TO FRONTEND
-- ============================================================================

-- Frontend expects permission objects with:
--   category: string (dashboard, campaigns, programs, tasks, wallet, users, settings)
--   level: string ('view' = read-only, 'full' = admin)

-- Partner_member permissions array should be:
-- [
--   {category: 'dashboard', level: 'view'},    → Dashboard readable
--   {category: 'campaigns', level: 'view'},    → Campaigns table readable
--   {category: 'programs', level: 'view'},     → Programs table readable
--   {category: 'tasks', level: 'view'},        → Tasks table readable
--   {category: 'wallet', level: 'view'},       → Wallets table readable
--   {category: 'users', level: 'view'},        → Profiles table readable
--   {category: 'settings', level: 'view'}      → Settings page (profile edit)
-- ]

-- All levels are 'view' because partner_members cannot perform admin operations
-- If write permissions needed in future, use level: 'write' for specific categories

-- ============================================================================
-- KEY FUNCTION: get_user_partner_id()
-- ============================================================================

-- This function is critical to all RLS policies for partner_member:

-- CREATE OR REPLACE FUNCTION public.get_user_partner_id(user_id UUID)
-- RETURNS UUID AS $$
-- BEGIN
--   RETURN (
--     SELECT partner_id FROM public.profiles 
--     WHERE id = user_id 
--     LIMIT 1
--   );
-- END;
-- $$ LANGUAGE plpgsql STABLE;

-- Usage in RLS policies:
--   partner_id = public.get_user_partner_id(auth.uid())
--
-- This compares the table's partner_id column with:
--   auth.uid() = the authenticated user's UUID (from JWT)
--   get_user_partner_id() = looks up that user's partner_id from profiles table
--
-- Result: Only rows matching the user's partner_id are returned
-- Security: Enforces partner data isolation at database level

-- ============================================================================
-- NO CHANGES REQUIRED
-- ============================================================================

-- All existing RLS policies already support partner_member role correctly.
-- Partner_members are automatically included in all policy conditions.
-- No policy modifications, drops, or recreations needed.
-- Just:
--   1. Create role record: INSERT INTO profiles (role = 'partner_member', ...)
--   2. Set permissions: permissions = jsonb_build_array(...)
--   3. Link to partner: partner_id = [partner_id_uuid]
--   4. RLS policies automatically apply via get_user_partner_id() check

-- ============================================================================
